services:

  db:
    image: postgres:16
    container_name: rubrika
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5435
    restart: unless-stopped
    networks:
      - rubrika-network
    volumes:
      - ./db/data:/var/lib/postgresql/18/docker


networks:
  rubrika-net:
    driver: bridge